on:
  push:
    branches: [ "master" ]
  workflow_dispatch:  # 手动触发

permissions:
  contents: read  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: npm install, build, and test
        run: |
          npm install -g pnpm
          pnpm install
          pnpm add sharp
          pnpm build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_TOKEN }} # 另外还支持 github_token 和 personal_token
          external_repository: xh-a/blog_web # 修改为你的 GitHub Pages 仓库
          publish_dir: ./dist
          keep_files: false
          publish_branch: master
